# Generated by Django 4.1.5 on 2023-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("roomid", models.TextField()),
                ("etage", models.TextField(default="pas d'etage")),
                ("date", models.TextField(default="pas de date")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Inactivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("date", models.TextField(default="pas de date")),
                ("etage_kdmap", models.TextField(default="pas d'etage")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("date", models.TextField(default="pas de texte")),
                ("etage_kdmap", models.TextField(default="pas d'etage")),
                ("ip", models.TextField(default="pas d'IP")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
