# Generated by Django 4.1.5 on 2023-02-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0003_alter_test_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["-created"]},
        ),
    ]
