# Generated by Django 4.1.5 on 2023-01-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0004_rename_snippet_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inactivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("date", models.TextField(default="pas de date")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("texte", models.TextField(default="pas de texte")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.TextField(default="pas de date"),
        ),
        migrations.AddField(
            model_name="booking",
            name="etage",
            field=models.IntegerField(default=-1),
        ),
    ]
