# Generated by Django 4.1.5 on 2023-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0005_inactivity_test_booking_date_booking_etage"),
    ]

    operations = [
        migrations.AddField(
            model_name="inactivity",
            name="etage_kdmap",
            field=models.TextField(default="pas d'identification de la kdmap"),
        ),
    ]
