# Generated by Django 4.1.5 on 2023-01-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0006_inactivity_etage_kdmap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inactivity",
            name="etage_kdmap",
            field=models.IntegerField(default=-50),
        ),
    ]
