# Generated by Django 4.1.5 on 2023-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0007_alter_inactivity_etage_kdmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="etage_kdmap",
            field=models.IntegerField(default=-50),
        ),
    ]
